runtime: python27
api_version: 1
threadsafe: true
env_variables:
  API_KEY: AIzaSyBVlucyJdUX6ZjwA17Bzl39faoRLSsk_q4
handlers:
- url: /
  static_files: dist/diario-clinico/index.html
  upload: dist/diario-clinico/index.html
- url: /
  static_dir: dist/diario-clinico