runtime: python27
api_version: 1
threadsafe: true
env_variables:
  API_KEY: #inserire qua api key
handlers:
- url: /.*
  static_files: dist/diario-clinico/index.html
  upload: dist/diario-clinico/index.html
- url: /.*
  static_dir: dist/diario-clinico
skip_files:
  - e2e/
  - node_modules/
  - src/
  - ^(.*/)?\..*$
  - ^(.*/)?.*\.json$
  - ^(.*/)?.*\.md$
  - ^(.*/)?.*\.yaml$
  - ^LICENSE